DROP TABLE IF EXISTS WREATH;
CREATE TABLE WREATH(
    ID UUID DEFAULT UUID_GENERATE_V4 (), 
    NAME VARCHAR(255) NOT NULL,
    SIZE INT NOT NULL, 
    PRICE INT NOT NULL,
    PICTUREURL TEXT[] NOT NULL,
    PRIMARY KEY (ID)
);
 
DROP TABLE IF EXISTS COLOR;
CREATE TABLE COLOR(
    WREATHID UUID NOT NULL, 
    COLOR VARCHAR(30) NOT NULL, 
    PRIMARY KEY (WREATHID, COLOR),
    CONSTRAINT FK_WREATH
        FOREIGN KEY(WREATHID)
            REFERENCES WREATH(ID)
            ON DELETE CASCADE
);

DROP TABLE IF EXISTS TIMEOFTHEYEAR;
CREATE TABLE TIMEOFTHEYEAR(
    WREATHID UUID NOT NULL,
    TIMEOFTHEYEAR VARCHAR(50) NOT NULL, 
    PRIMARY KEY (WREATHID, TIMEOFTHEYEAR),
    CONSTRAINT FK_WREATH
        FOREIGN KEY(WREATHID)
            REFERENCES WREATH(ID)
            ON DELETE CASCADE
);